version: '3'

services:
  postgres-products:
   image: postgres:9.6
   domainname: products
   ports:
    - "5433:5432"
   environment:
    - POSTGRES_USER=postgres
    - POSTGRES_PASSWORD=postgres
   healthcheck:
    test: ["CMD", "pg_isready", "-q", "-U", "products"]
    interval: 5s
    timeout: 1s
    retries: 2
  flyway1:
   image: boxfuse/flyway
   command: -url=jdbc:postgresql://products:5432/postgres -schemas=public -user=postgres -password=postgres -connectRetries=30 migrate
   volumes:
    - ./flyway/products:/flyway/sql
   depends_on:
    - postgres-products

 postgres-users:
  image: postgres:9.6
  domainname: users
  ports:
   - "5434:5432"
  environment:
   - POSTGRES_USER=postgres
   - POSTGRES_PASSWORD=postgres
  healthcheck:
   test: ["CMD", "pg_isready", "-q", "-U", "users"]
   interval: 5s
   timeout: 1s
   retries: 2
 flyway2:
  image: boxfuse/flyway
  command: -url=jdbc:postgresql://users:5432/postgres -schemas=public -user=postgres -password=postgres -connectRetries=30 migrate
  volumes:
   - ./flyway/users:/flyway/sql
  depends_on:
   - postgres-users

 zookeeper:
   image: confluentinc/cp-zookeeper:5.4.0
  environment:
   ZOOKEEPER_CLIENT_PORT: 2181
   ZOOKEEPER_TICK_TIME: 2000
 kafka:
   image: confluentinc/cp-kafka:5.4.0
   ports:
    - 9092:9092
   environment:
    KAFKA_BROKER_ID: 1
    KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
    KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:29092,PLAINTEXT_HOST://0.0.0.0:9092
    KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:29092,PLAINTEXT_HOST://localhost:9092
    KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
    KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
    KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
 connect:
   image: debezium/connect:1.4
   ports:
    - 8083:8083
  links:
   - kafka
  environment:
   - BOOTSTRAP_SERVERS=PLAINTEXT://kafka:29092
   - GROUP_ID=1
   - CONFIG_STORAGE_TOPIC=dbz_connect_configs
   - OFFSET_STORAGE_TOPIC=dbz_connect_offsets
   - STATUS_STORAGE_TOPIC=dbz_connect_statuses