version: '3'

services:
  flyway1:
   image: boxfuse/flyway
   command: -url=jdbc:postgresql://products:5432/postgres -schemas=public -user=postgres -password=postgres -connectRetries=30 migrate
   volumes:
    - ./flyway/products:/flyway/sql
   depends_on:
    - postgres-products
 flyway2:
  image: boxfuse/flyway
  command: -url=jdbc:postgresql://users:5432/postgres -schemas=public -user=postgres -password=postgres -connectRetries=30 migrate
  volumes:
   - ./flyway/users:/flyway/sql
  depends_on:
   - postgres-users